### ISSUE TITLE
No bluetooth in Opensuse 42.1 (kernel 4.1.12)

### ISSUE THREAD

**Issue by txutxifel** [neurobin/MT7630E#10] opened 2015-11-15 17:46 UTC
First
Thank for your job. I used your last patch in my PC and wireless connection is more stable.

However,I have just updated my PC (Opensuse Leap 42.1 Kde) and I can't get my bluetooth working in the last kernel 4.1.12:

Linux PC003 4.1.12-1-default #1 SMP PREEMPT Thu Oct 29 06:43:42 UTC 2015 (e24bad1) x86_64 x86_64 x86_64 GNU/Linux

I have done some test. Mt76xx is never used by bluetooth:

btusb 53248 0
btbcm 16384 1 btusb
btintel 16384 1 btusb
bluetooth 532480 9 bnep,btbcm,btusb,btintel

I tried to blacklist btbtcm and btusb, but mt76xx is not used either.

With:
sudo hciconfig hci0 up
Can't init device hci0: Invalid request code (56)

With my old kernel (3.16) bluetooth is working well

Any Idea?

Cheers

**Comment by fabiocarrara** [comment] 2015-11-16 16:49
Same problem with Ubuntu 15.10 and kernel 4.2.0.. The error seems to be caused by an unsupported HCI command. I've reported more infos about the error in #6 using **btmon**. Hope it helps to identify the problem.

**Comment by glats** [comment] 2016-04-05 14:35
FYI They find a solution #6
Maybe you can try it

**Comment by neurobin** [comment] 2016-05-22 17:27
I will close this issue for now. For more info use the #6 .

To apply the patch read [this](https://github.com/neurobin/MT7630E/wiki/Get-bluetooth-working-in-Linux-kernel--with-mt7630e)

**Closed as completed** 2016-05-22 17:27 UTC
